version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
    - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
  producer:
    build:
      context: producer/
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
  consumer:
    build:
      context: consumer/
    depends_on:
      - rabbitmq
